apiVersion: v1
kind: ConfigMap
metadata:
  name: lake-uuids
  namespace: wooglife
data:
  LARGE_WOOG_UUID: {{ .Values.lakeuuid.largeWoog }}
  ARHEILGER_MUEHLCHEN_UUID: {{ .Values.lakeuuid.arheilgerMuehlchen }}
  ALSTER_UUID: {{ .Values.lakeuuid.alster }}
  CUXHAVEN_UUID: {{ .Values.lakeuuid.cuxhaven }}
  POTSDAM_UUID: {{ .Values.lakeuuid.potsdam }}
  AARE_UUID: {{ .Values.lakeuuid.aare }}
  COLOGNE_UUID: {{ .Values.lakeuuid.cologne }}
  BLAARMEERSEN_UUID: {{ .Values.lakeuuid.blaarmeersen }}
  SANTANDER_UUID: {{ .Values.lakeuuid.santander }}
  HERAKLION_UUID: {{ .Values.lakeuuid.heraklion }}
  HUSUM_UUID: {{ .Values.lakeuuid.husum }}
  VANCOUVER_UUID: {{ .Values.lakeuuid.vancouver }}
  SORRENTO_UUID: {{ .Values.lakeuuid.sorrento }}
