name: Build/Publish docker image

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: update values
        run: sed -i -e "s/{{API_KEY}}/${{ secrets.API_KEY }}/g" values.yaml
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade config . --install --wait --atomic --values=./values.yaml
          kubeconfig: '${{ secrets.KUBECONFIG }}'
