name: deploy helm chart

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade config . --install --wait --atomic --namespace=wooglife
          kubeconfig: '${{ secrets.KUBECONFIG_RAW }}'
