name: deploy helm chart

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: update values
        run: |
          sed -i -e "s/__API_KEY__/${{ secrets.API_KEY }}/g" values.yaml
      - uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade config . --install --wait --atomic --namespace=wooglife
          kubeconfig: '${{ secrets.KUBECONFIG_RAW }}'
