name: lint helm chart

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm lint
